services:
  - type: web
    name: dashboard-auditoria-novo
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    python:
      version: "3.10.13"
