services:
  - type: web
    name: dashboardauditorialm
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    pythonVersion: 3.10.13
